In [ ]:
import pandas as pd 
path="/content/Drive/my drive/machine learning/COVID19_line_list_data.csv"
dataset=pd.read_csv(path) 
dataset

        id  case_in_country  ... Unnamed: 25  Unnamed: 26
0        1              NaN  ...         NaN          NaN
1        2              NaN  ...         NaN          NaN
2        3              NaN  ...         NaN          NaN
3        4              NaN  ...         NaN          NaN
4        5              NaN  ...         NaN          NaN
...    ...              ...  ...         ...          ...
1080  1081              2.0  ...         NaN          NaN
1081  1082              1.0  ...         NaN          NaN
1082  1083              1.0  ...         NaN          NaN
1083  1084              1.0  ...         NaN          NaN
1084  1085              1.0  ...         NaN          NaN

[1085 rows x 27 columns]

In [ ]:
dataset.head()

   id  case_in_country reporting date  ...  Unnamed: 24 Unnamed: 25 Unnamed: 26
0   1              NaN      1/20/2020  ...          NaN         NaN         NaN
1   2              NaN      1/20/2020  ...          NaN         NaN         NaN
2   3              NaN      1/21/2020  ...          NaN         NaN         NaN
3   4              NaN      1/21/2020  ...          NaN         NaN         NaN
4   5              NaN      1/21/2020  ...          NaN         NaN         NaN

[5 rows x 27 columns]

In [ ]:
dataset.shape

(1085, 27)

In [ ]:
dataset.isnull().sum()

id                          0
case_in_country           197
reporting date              1
Unnamed: 3               1085
summary                     5
location                    0
country                     0
gender                    183
age                       242
symptom_onset             522
If_onset_approximated     525
hosp_visit_date           578
exposure_start            957
exposure_end              744
visiting Wuhan              0
from Wuhan                  4
death                       0
recovered                   0
symptom                   815
source                      0
link                        0
Unnamed: 21              1085
Unnamed: 22              1085
Unnamed: 23              1085
Unnamed: 24              1085
Unnamed: 25              1085
Unnamed: 26              1085
dtype: int64

In [ ]:
dataset.max()

id                                                                    1085
case_in_country                                                       1443
Unnamed: 3                                                             NaN
location                                                            Zhuhai
country                                                            Vietnam
age                                                                     96
If_onset_approximated                                                    1
visiting Wuhan                                                           1
from Wuhan                                                               1
death                                                            2/28/2020
recovered                                                        2/28/2020
source                                                                  新浪
link                     https://www3.nhk.or.jp/nhkworld/en/news/202001...
Unnamed: 21                                                            NaN
Unnamed: 22                                                            NaN
Unnamed: 23                                                            NaN
Unnamed: 24                                                            NaN
Unnamed: 25                                                            NaN
Unnamed: 26                                                            NaN
dtype: object

In [ ]:
dataset.min()

id                                                                       1
case_in_country                                                          1
Unnamed: 3                                                             NaN
location                                                       Afghanistan
country                                                        Afghanistan
age                                                                   0.25
If_onset_approximated                                                    0
visiting Wuhan                                                           0
from Wuhan                                                               0
death                                                                    0
recovered                                                                0
source                                                                 ABC
link                     http://behdasht.gov.ir/news/%DA%A9%D8%B1%D9%88...
Unnamed: 21                                                            NaN
Unnamed: 22                                                            NaN
Unnamed: 23                                                            NaN
Unnamed: 24                                                            NaN
Unnamed: 25                                                            NaN
Unnamed: 26                                                            NaN
dtype: object

In [ ]:
dataset.describe

<bound method NDFrame.describe of         id  case_in_country  ... Unnamed: 25  Unnamed: 26
0        1              NaN  ...         NaN          NaN
1        2              NaN  ...         NaN          NaN
2        3              NaN  ...         NaN          NaN
3        4              NaN  ...         NaN          NaN
4        5              NaN  ...         NaN          NaN
...    ...              ...  ...         ...          ...
1080  1081              2.0  ...         NaN          NaN
1081  1082              1.0  ...         NaN          NaN
1082  1083              1.0  ...         NaN          NaN
1083  1084              1.0  ...         NaN          NaN
1084  1085              1.0  ...         NaN          NaN

[1085 rows x 27 columns]>

In [ ]:
data=dataset.dropna()

In [ ]:
data.shape

(0, 27)

In [ ]:
dataset.dropna(axis=0,subset=['China'],inplace=True)

In [ ]:
dataset.shape

(1085, 27)

In [ ]:
Fitur = ['age','gender']
X=data[Fitur]
X

Empty DataFrame
Columns: [age, gender]
Index: []